name: Build OBS Timestamp Plugin

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup OBS Studio
        uses: obsproject/obs-studio-ci@v1
        with:
          obs-version: '32.0.1'
          obs-deps-version: '2024-08-15'

      - name: Configure
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/obs-studio"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-timestamp-plugin-windows
          path: |
            build/Release/*.dll
            data/

  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libobs-dev obs-studio

      - name: Configure
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-timestamp-plugin-linux
          path: |
            build/*.so
            data/

  macos:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install cmake obs

      - name: Configure
        run: cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/local

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-timestamp-plugin-macos
          path: |
            build/*.so
            data/
